[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sfit-sgf"
version = "0.0.1"
description = "SFIT Semantic Gauge Field core utilities"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
