name: CI

on:
  push:
    branches: [main, master]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements-dev.txt
            pyproject.toml

      - name: Install package + dev deps
        run: |
          python -m pip install -U pip wheel
          python -m pip install -e .
          python -m pip install -r requirements-dev.txt

      # Optional: quick smoke test of examples (Linux only)
      - name: Run quickstart examples
        if: runner.os == 'Linux'
        run: |
          python examples/quickstart_alpha_rho_S.py
          python examples/quickstart_davis_kahan.py
          python examples/quickstart_weighted_projector.py

      - name: Run tests with coverage (enforce 90%)
        run: |
          python -m pytest --maxfail=1 \
            --cov=src/sfit_sgf \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-fail-under=90 -q

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-py${{ matrix.python-version }}
          path: coverage.xml
