jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package + dev deps
        run: |
          python -m pip install -U pip
          python -m pip install -e .
          python -m pip install -r requirements-dev.txt

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=src/sfit_sgf --cov-report=term-missing --cov-fail-under=90 -q

       - name: Run φ-field smoke (Maxwell + entropy)
        run: |
          python examples/ci_phi_smoke.py

      - name: Run Φ-field quickstart (smoke)
        run: |
          python examples/phi_flow_minimal.py

      - name: Export coverage XML
        if: always()
        run: |
          python -m coverage xml

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-py${{ matrix.python-version }}
          path: coverage.xml
      - name: Run phi point-source (Maxwell sanity)
        run: |
          python examples/phi_point_source.py --steps 200 --nu 0

      - name: Run phi point-source (entropy descent smoke)
        run: |
          python examples/phi_point_source.py --steps 200 --nu 1e-2
